import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import Banner from '@/components/Banner/Banner'
import Description from '@/components/Description/Description'
import Gallery from '@/components/Gallery/Gallery'
import Footer from '@/components/Footer/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Pixion Films</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/pixion-films-ico.svg" />
      </Head>
      <Layout>
        <Banner />
        <Description />
        <Gallery />
        <Footer />
      </Layout>
    </>
  )
}
